name: Chunk-Claim
author: Paul2708
version: 0.2.1
main: de.paul2708.claim.ClaimPlugin
api-version: 1.13

depend: [WorldGuard, WorldEdit]

commands:
  chunk:
    description: Claim den aktuellen Chunk
  live:
    description: Setzte deinen Status auf Live