name: Chunk-Claim
author: Paul2708
version: 2.0.1
main: de.paul2708.claim.ClaimPlugin
api-version: 1.13

depend: [WorldGuard, WorldEdit]

commands:
  chunk:
    description: Claim den aktuellen Chunk
  live:
    description: Setzte deinen Status auf Live
  tphelp:
    description: Teleportiere dich zu einem Spieler in deiner Umgebung
    aliases: [tphilfe, teleporthelp, teleporthilfe]